# Generated by Django 3.1.7 on 2021-03-21 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Name',
            new_name='name',
        ),
    ]
