# Generated by Django 3.2.3 on 2021-08-28 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pure_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='authors',
            new_name='author',
        ),
    ]
